server:
  port: 8088
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - beans
          - health
          - metrics
          - env
